#!/bin/bash
#author:Bao Ning
#2017.8.21

f() {
for((i=0; i<=10; i++)); do
	echo $i
	sleep 5
done
}

g() {
for((i=0; i<=10; i++)); do
	echo "g $i"
	sleep 1
done
}

ps
f&
pid1=$!
ps
echo "pid1 = $pid1"
g&
pid2=$!
ps
echo "pid2 = $pid2"
wait $pid2
ps
kill $pid1
ps

